version: "3.8"
services:
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
  web:
    image: web-react
    build: ./my-new-app-docker
    restart: unless-stopped
    env_file: ./.env 
    volumes:
        - './my-new-app-docker:/app'
        - /app/node_modules
    ports:
       - ${FRONT_END_PORT}:${FRONT_END_PORT}
    stdin_open: true
    tty: true
    environment:
        - CHOKIDAR_USEPOLLING=true  
  app:
    image: node-server
    depends_on:
      - mongodb
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    env_file: ./.env
    ports:
       - ${BACK_END_PORT}:${BACK_END_PORT}
    environment:
      - DB_HOST=mongodb
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=hello
      - DB_PORT=27017
    stdin_open: true
    tty: true

volumes:
  db: